In [1]:
import polars as pl
import pandas as pd
import numpy as np
pd.set_option("display.max_columns", None)

#np.set_printoptions(suppress=True, precision=3)
#pd.options.display.float_format = '{:.0f}'.format

## SARIMA

In [2]:
sarima = pd.read_parquet("results/SARIMA-short-time.parquet")
sarima

        node          mae           mse        r2      mape   model
0  125960550     5.157985  4.131267e+01 -0.106240  0.520130  SARIMA
1  230565994    18.917946  6.001879e+02 -1.485901  0.995000  SARIMA
2  258781031   751.590873  7.806323e+05 -2.304690  0.703686  SARIMA
3   43768720  1496.631493  3.022672e+06 -3.046599  0.962821  SARIMA
4   44072192   103.392079  1.441076e+04 -2.913646  0.988947  SARIMA
5   44783654   201.510833  5.703517e+04 -2.461737  1.009762  SARIMA
6   44783914   242.928134  9.172523e+04 -1.470166  0.793290  SARIMA
7   44784438   215.166685  6.265714e+04 -2.974569  0.970938  SARIMA
8   45833547    72.918679  7.650756e+03 -2.232412  1.020078  SARIMA
9   47568123   125.787035  1.927480e+04 -4.560282  1.017736  SARIMA

In [3]:
sarima["mae"].mean(), sarima["mape"].mean(), sarima["mse"].mean(), sarima["r2"].mean()

(323.4001742458498, 0.8982388527872678, 405669.9461448045, -2.355624289523335)

## MLP

In [4]:
mlp = pd.read_parquet("results/MLP-short-time.parquet")
mlp.head()

        node           mae           mse            r2          mape model
0  125960550  5.306115e+00  4.205412e+01 -1.249924e-01  6.204056e-01   MLP
1  230565994  1.084060e+17  2.648320e+35 -1.095774e+33  1.092280e+16   MLP
2  258781031  9.670453e+02  1.186166e+06 -4.015308e+00  9.152361e-01   MLP
3   43768720  1.242244e+03  2.288493e+06 -2.060549e+00  8.548973e-01   MLP
4   44072192  1.527648e+02  4.663901e+04 -1.165959e+01  2.755733e+00   MLP

In [5]:
np.mean(mlp.mae.values)

1.0840597957339278e+16

In [6]:
print(f"{mlp['mae'].mean():,.0f}")

10,840,597,957,339,278

In [7]:
print(f"{mlp['mae'].mean():.0f}")

10840597957339278

In [8]:
valores = (mlp["mae"].mean(), mlp["mape"].mean(), mlp["mse"].mean(), mlp["r2"].mean())
valores

(1.0840597957339278e+16,
 1092279547094632.8,
 2.6483197781422444e+34,
 -1.0957736898625555e+32)

In [9]:
valores = np.array(valores, dtype=np.float64)

print(valores)

[ 1.08405980e+16  1.09227955e+15  2.64831978e+34 -1.09577369e+32]

In [10]:
# Lê o arquivo Parquet
mlp = pl.read_parquet("results/MLP-short-time.parquet")

# Calcula a média de todas as colunas numéricas
# means = mlp.select([
#     pl.col(pl.Float64).mean().round(3).alias(f"{col.name}_mean")
#     for col in mlp.schema.items()
#     if isinstance(col[1], pl.Float64)
# ])

# # Mostra o resultado
# print(means)

In [11]:
mlp.select([
    pl.col("mae").mean().round(3),
    pl.col("mse").mean().round(3),
    pl.col("r2").mean().round(3),
    pl.col("mape").mean().round(3)
])

shape: (1, 4)
┌───────────┬───────────┬────────────┬───────────┐
│ mae       ┆ mse       ┆ r2         ┆ mape      │
│ ---       ┆ ---       ┆ ---        ┆ ---       │
│ f64       ┆ f64       ┆ f64        ┆ f64       │
╞═══════════╪═══════════╪════════════╪═══════════╡
│ 1.0841e16 ┆ 2.6483e34 ┆ -1.0958e32 ┆ 1.0923e15 │
└───────────┴───────────┴────────────┴───────────┘

In [12]:
means_dict = mlp.select([
    pl.col("mae").mean(),
    pl.col("mse").mean(),
    pl.col("r2").mean(),
    pl.col("mape").mean()
]).to_dict(as_series=False)

# Formatando e imprimindo sem notação científica
for k, v in means_dict.items():
    print(f"{k}: {v[0]:,.3f}")

mae: 10,840,597,957,339,280.000
mse: 26,483,197,781,422,444,014,826,292,567,343,104.000
r2: -109,577,368,986,255,549,944,196,373,676,032.000
mape: 1,092,279,547,094,632.375

## LSTM

In [13]:
lstm = pd.read_parquet("results/LSTM-short-time.parquet")
lstm.head()

        node          mae           mse        r2      mape model
0  125960550     5.436322  4.692825e+01 -0.255381  0.563083  LSTM
1  230565994    11.039452  2.914917e+02 -0.206082  0.652601  LSTM
2  258781031  1038.338379  1.314662e+06 -4.558613  0.987586  LSTM
3   43768720  1514.337280  3.040981e+06 -3.066900  0.989945  LSTM
4   44072192    85.381218  1.097078e+04 -1.977884  0.726549  LSTM

In [14]:
lstm["mae"].mean(), lstm["mape"].mean(), lstm["mse"].mean(), lstm["r2"].mean()

(346.79999856948854, 0.7945203483104706, 460337.8426815033, -2.091480779647827)

## GRU

In [15]:
gru = pd.read_parquet("results/GRU-short-time.parquet")
gru.head()

        node          mae           mse        r2      mape model
0  125960550     6.228364  6.531496e+01 -0.747245  0.466649   GRU
1  230565994    10.880714  2.786791e+02 -0.153068  0.672237   GRU
2  258781031  1030.508423  1.298459e+06 -4.490101  0.977419   GRU
3   43768720  1505.154907  3.013232e+06 -3.029789  0.979866   GRU
4   44072192    86.138115  1.110192e+04 -2.013481  0.737360   GRU

In [16]:
gru["mae"].mean(), gru["mape"].mean(), gru["mse"].mean(), gru["r2"].mean()

(345.56918501853943, 0.7883456736803055, 456006.101750946, -2.147892189025879)