In [1]:
import polars as pl
import pandas as pd
import numpy as np
pd.set_option("display.max_columns", None)

#np.set_printoptions(suppress=True, precision=3)
#pd.options.display.float_format = '{:.0f}'.format

## ETS

In [2]:
ets = pd.read_parquet("results/ETS-short-time.parquet")
ets.head()

        node         mae            mse        r2      mape model
0  125960550    3.127299      18.822875  0.495975  0.422105   ETS
1  230565994    4.805057      48.304744  0.799928  0.418623   ETS
2  258781031  150.704710   83971.150512  0.644521  0.245857   ETS
3   43768720  334.025782  339735.902333  0.545179  0.508730   ETS
4   44072192   16.985113     966.412169  0.737544  0.199451   ETS

In [3]:
ets["mae"].mean(), ets["mape"].mean(), ets["mse"].mean(), ets["r2"].mean()

(66.26327930890676, 0.31961401251337046, 44257.13522828347, 0.7052963836611346)

In [4]:
ets["mae"].std(), ets["mape"].std(), ets["mse"].std(), ets["r2"].std()

(103.57043753344264,
 0.10584068634733454,
 106976.80537603013,
 0.10754229786501268)

## PropHet

In [5]:
proph = pd.read_parquet("results/PROPHET-short-time.parquet")
proph.head()

        node          mae           mse        r2      mape    model
0  125960550     7.783641  9.886713e+01 -1.647390  0.700797  Prophet
1  230565994    16.785103  4.835257e+02 -1.002701  1.225861  Prophet
2  258781031   612.766594  5.512239e+05 -1.333524  0.814939  Prophet
3   43768720  1115.940083  1.821316e+06 -1.438285  1.308869  Prophet
4   44072192    72.923564  7.580323e+03 -1.058649  1.016284  Prophet

In [6]:
proph["mae"].mean(), proph["mape"].mean(), proph["mse"].mean(), proph["r2"].mean()

(250.46762871567776, 1.1005576268602435, 254178.688975707, -1.2521610790130215)

In [7]:
proph["mae"].std(), proph["mape"].std(), proph["mse"].std(), proph["r2"].std()

(351.2170435784196, 0.2827858779734023, 575763.0005498988, 0.1972008195937511)

## SARIMA

In [8]:
sarima = pd.read_parquet("results/SARIMA-short-time.parquet")
sarima

        node         mae           mse        r2      mape   model
0  125960550    6.971627  6.558523e+01 -0.756192  0.998429  SARIMA
1  230565994   18.628735  5.899863e+02 -1.443647  0.977590  SARIMA
2  258781031  930.555054  1.116266e+06 -3.725546  0.876224  SARIMA
3   43768720  578.445711  5.302310e+05  0.290154  0.776147  SARIMA
4   44072192   98.191012  1.302790e+04 -2.538093  0.934375  SARIMA
5   44783654  138.822584  3.108401e+04 -0.886637  0.696142  SARIMA
6   44783914   96.397224  1.748185e+04  0.529213  0.485113  SARIMA
7   44784438  202.474050  5.614347e+04 -2.561384  0.916427  SARIMA
8   45833547   54.909189  4.654630e+03 -0.966562  0.779701  SARIMA
9   47568123   35.419653  2.038365e+03  0.411985  0.439390  SARIMA

In [9]:
sarima["mae"].mean(), sarima["mape"].mean(), sarima["mse"].mean(), sarima["r2"].mean()

(216.081483981022, 0.7879536334675601, 177158.2965337545, -1.1646709866625973)

In [10]:
sarima["mae"].std(), sarima["mape"].std(), sarima["mse"].std(), sarima["r2"].std()

(301.3832235112529, 0.1965943804487564, 367871.38855780655, 1.4231423394680722)

## MLP

In [11]:
mlp = pd.read_parquet("results/MLP-short-time.parquet")
mlp.head()

        node           mae           mse            r2          mape model
0  125960550  5.306115e+00  4.205412e+01 -1.249924e-01  6.204056e-01   MLP
1  230565994  1.084060e+17  2.648320e+35 -1.095774e+33  1.092280e+16   MLP
2  258781031  9.670453e+02  1.186166e+06 -4.015308e+00  9.152361e-01   MLP
3   43768720  1.242244e+03  2.288493e+06 -2.060549e+00  8.548973e-01   MLP
4   44072192  1.527648e+02  4.663901e+04 -1.165959e+01  2.755733e+00   MLP

In [13]:
print(f"{mlp['mae'].mean():.0f}")

10840597957339278

In [14]:
valores = (mlp["mae"].mean(), mlp["mape"].mean(), mlp["mse"].mean(), mlp["r2"].mean())
valores

(1.0840597957339278e+16,
 1092279547094632.8,
 2.6483197781422444e+34,
 -1.0957736898625555e+32)

In [15]:
valores = (mlp["mae"].std(), mlp["mape"].std(), mlp["mse"].std(), mlp["r2"].std())
valores

(3.4280980743359024e+16,
 3454091210436184.0,
 8.374722471401296e+34,
 3.465140660052633e+32)

## LSTM

In [18]:
lstm = pd.read_parquet("results/LSTM-short-time.parquet")
lstm.head()

        node          mae           mse        r2      mape model
0  125960550     5.436322  4.692825e+01 -0.255381  0.563083  LSTM
1  230565994    11.039452  2.914917e+02 -0.206082  0.652601  LSTM
2  258781031  1038.338379  1.314662e+06 -4.558613  0.987586  LSTM
3   43768720  1514.337280  3.040981e+06 -3.066900  0.989945  LSTM
4   44072192    85.381218  1.097078e+04 -1.977884  0.726549  LSTM

In [19]:
lstm["mae"].mean(), lstm["mape"].mean(), lstm["mse"].mean(), lstm["r2"].mean()

(346.79999856948854, 0.7945203483104706, 460337.8426815033, -2.091480779647827)

In [20]:
lstm["mae"].std(), lstm["mape"].std(), lstm["mse"].std(), lstm["r2"].std()

(509.62761159898633,
 0.14401350819723138,
 993045.0474280857,
 1.3388881007816145)

## GRU

In [21]:
gru = pd.read_parquet("results/GRU-short-time.parquet")
gru.head()

        node          mae           mse        r2      mape model
0  125960550     6.228364  6.531496e+01 -0.747245  0.466649   GRU
1  230565994    10.880714  2.786791e+02 -0.153068  0.672237   GRU
2  258781031  1030.508423  1.298459e+06 -4.490101  0.977419   GRU
3   43768720  1505.154907  3.013232e+06 -3.029789  0.979866   GRU
4   44072192    86.138115  1.110192e+04 -2.013481  0.737360   GRU

In [22]:
gru["mae"].mean(), gru["mape"].mean(), gru["mse"].mean(), gru["r2"].mean()

(345.56918501853943, 0.7883456736803055, 456006.101750946, -2.147892189025879)

In [23]:
gru["mae"].std(), gru["mape"].std(), gru["mse"].std(), gru["r2"].std()

(505.81416414801237, 0.1578045877938574, 983448.5313876251, 1.2599568439398965)

## Chronos

In [24]:
chronos = pd.read_parquet("results/CRHONOS-short-time.parquet")
chronos.head()

        node         mae           mse        r2      mape        model
0  125960550    6.160245  6.189288e+01 -0.657321  0.536559  cronos-BASE
1  230565994   14.334797  3.865694e+02 -0.601121  1.046061  cronos-BASE
2  258781031  314.608093  1.733610e+05  0.266102  0.425684  cronos-BASE
3   43768720  944.357971  1.314671e+06 -0.760015  0.839489  cronos-BASE
4   44072192   56.759014  4.519636e+03 -0.227434  0.803945  cronos-BASE

In [25]:
chronos["mae"].mean(), chronos["mape"].mean(), chronos["mse"].mean(), chronos["r2"].mean()

(186.85472803115846,
 0.8311403691768646,
 160742.8852657318,
 -0.49635141491889956)

In [26]:
chronos["mae"].std(), chronos["mape"].std(), chronos["mse"].std(), chronos["r2"].std()

(281.30098017333484,
 0.25993835853264236,
 408778.12960001343,
 0.4031195937119417)