In [1]:
import pandas as pd
pd.set_option("display.max_columns", None)

## SARIMA

In [2]:
sarima = pd.read_parquet("results/SARIMA-long-time.parquet")
sarima.head()

        node         mae           mse        r2      mape   model
0  125960550   11.356673  1.575799e+02 -4.361174  0.970403  SARIMA
1  230565994    7.805355  1.207751e+02  0.502888  0.409115  SARIMA
2  258781031  782.862602  8.382852e+05 -2.644062  0.637810  SARIMA
3   43768720  943.597705  1.260216e+06 -0.661199  0.553149  SARIMA
4   44072192   99.527906  1.350636e+04 -2.741304  0.951975  SARIMA

In [3]:
sarima["mae"].mean(), sarima["mape"].mean(), sarima["mse"].mean(), sarima["r2"].mean()

(273.6929401527031, 0.8195004360133036, 237269.7152679834, -2.3988555998383063)

In [4]:
sarima["mae"].std(), sarima["mape"].std(), sarima["mse"].std(), sarima["r2"].std()

(325.14744356425916,
 0.21403631043022273,
 440869.75934482156,
 1.485269765426499)

## PROPHET

In [5]:
prophet = pd.read_parquet("results/PROPHET-long-time.parquet")
prophet.head()

        node          mae           mse        r2      mape    model
0  125960550     8.557222  1.212139e+02 -3.123930  0.790835  Prophet
1  230565994    18.489625  5.852807e+02 -1.409023  1.288161  Prophet
2  258781031   852.317571  1.083077e+06 -3.708182  0.830188  Prophet
3   43768720  1428.435871  3.059482e+06 -3.032968  1.019412  Prophet
4   44072192    91.970727  1.365986e+04 -2.783824  1.030094  Prophet

In [15]:
prophet["mae"].mean(), prophet["mape"].mean(), prophet["mse"].mean(), prophet["r2"].mean()

(322.36972757254387,
 1.0310381181820583,
 441501.61129123357,
 -2.747661694227809)

In [6]:
prophet["mae"].std(), prophet["mape"].std(), prophet["mse"].std(), prophet["r2"].std()

(459.07126303459603,
 0.18537893838656846,
 977805.6767851256,
 0.6859803883018034)

## ETS

In [7]:
ets = pd.read_parquet("results/ETS-long-time.parquet")
ets.head()

        node         mae            mse        r2      mape model
0  125960550    2.930875      16.445592  0.440489  0.319465   ETS
1  230565994    3.918606      36.329537  0.850467  0.247583   ETS
2  258781031   97.114342   42136.298868  0.816832  0.150435   ETS
3   43768720  181.159948  153214.192382  0.798035  0.237946   ETS
4   44072192   17.956345     859.611521  0.761885  0.223537   ETS

In [8]:
ets["mae"].mean(), ets["mape"].mean(), ets["mse"].mean(), ets["r2"].mean()

(43.32263358307324, 0.21607360999160813, 20767.10257274901, 0.7888596411478591)

In [9]:
ets["mae"].std(), ets["mape"].std(), ets["mse"].std(), ets["r2"].std()

(55.56627870801755, 0.06038944783833723, 48280.8435946691, 0.1261207502685516)

## MLP

In [14]:
mlp = pd.read_parquet("results/MLP-long-time.parquet")
mlp.head()

        node          mae           mse         r2      mape model
0  125960550     6.191991  6.200018e+01  -1.110384  0.480837   MLP
1  230565994    37.912624  4.140325e+03 -16.037693  4.703748   MLP
2  258781031  1041.947876  1.312282e+06  -4.712078  0.961472   MLP
3   43768720  1498.926880  2.977606e+06  -2.929089  0.867413   MLP
4   44072192    60.753605  5.572439e+03  -0.544535  0.833653   MLP

In [15]:
mlp["mae"].mean(), mlp["mape"].mean(), mlp["mse"].mean(), mlp["r2"].mean()

(59810.19528784752, 646.7259085446597, 220165016172.8915, -12802088.770622874)

In [16]:
mlp["mae"].std(), mlp["mape"].std(), mlp["mse"].std(), mlp["r2"].std()

(188032.23542195256, 2041.3182635989006, 696221360008.0743, 40483748.18240024)

## LSTM

In [18]:
lstm = pd.read_parquet("results/LSTM-long-time.parquet")
lstm.head()

        node          mae           mse        r2      mape model
0  125960550     5.577831  5.180875e+01 -0.763484  0.488127  LSTM
1  230565994    11.508994  3.085341e+02 -0.269637  0.656303  LSTM
2  258781031  1066.038574  1.366177e+06 -4.946671  0.988144  LSTM
3   43768720  1637.347656  3.438745e+06 -3.537583  0.990983  LSTM
4   44072192    83.582268  1.057674e+04 -1.931597  0.708885  LSTM

In [19]:
lstm["mae"].mean(), lstm["mape"].mean(), lstm["mse"].mean(), lstm["r2"].mean()

(364.78130407333373,
 0.7897243946790695,
 506182.84195556643,
 -2.3298051595687865)

In [20]:
lstm["mae"].std(), lstm["mape"].std(), lstm["mse"].std(), lstm["r2"].std()

(544.2490319152558, 0.15930660212183786, 1112976.945824539, 1.3834643535849287)

## GRU

In [21]:
gru = pd.read_parquet("results/GRU-long-time.parquet")
gru.head()

        node          mae           mse        r2      mape model
0  125960550     5.602227  5.278165e+01 -0.796600  0.441580   GRU
1  230565994    10.937225  2.801380e+02 -0.152785  0.681046   GRU
2  258781031  1058.061035  1.349232e+06 -4.872915  0.978135   GRU
3   43768720  1628.242432  3.409010e+06 -3.498347  0.982095   GRU
4   44072192    85.060402  1.083170e+04 -2.002265  0.729783   GRU

In [22]:
gru["mae"].mean(), gru["mape"].mean(), gru["mse"].mean(), gru["r2"].mean()

(363.3101372241974, 0.7893513292074203, 501545.3331302643, -2.3276140332221984)

In [23]:
gru["mae"].std(), gru["mape"].std(), gru["mse"].std(), gru["r2"].std()

(540.5953824515971, 0.16382141720658655, 1102797.516769596, 1.3826131361021563)

## Chronos

In [24]:
chronos = pd.read_parquet("results/CRHONOS-long-time.parquet")
chronos.head()

        node          mae           mse         r2      mape   model
0  125960550    33.465668  1.968526e+03 -65.973045  4.007134  SARIMA
1  230565994    17.709558  5.622633e+02  -1.314284  1.334176  SARIMA
2  258781031   566.579102  4.625947e+05  -1.010919  0.629109  SARIMA
3   43768720  3799.901367  1.890726e+07 -23.923290  4.449543  SARIMA
4   44072192    60.661293  5.614787e+03  -0.555314  0.715814  SARIMA

In [25]:
chronos["mae"].std(), chronos["mape"].std(), chronos["mse"].std(), chronos["r2"].std()

(1164.9579807177308, 1.4267781927623728, 5957881.863386953, 20.84547356271113)