In [2]:
import pandas as pd
pd.set_option("display.max_columns", None)

## SARIMA

In [4]:
sarima = pd.read_parquet("results/SARIMA-long-time.parquet")
sarima.head()

        node         mae           mse        r2      mape   model
0  125960550   11.356673  1.575799e+02 -4.361174  0.970403  SARIMA
1  230565994    7.805355  1.207751e+02  0.502888  0.409115  SARIMA
2  258781031  782.862602  8.382852e+05 -2.644062  0.637810  SARIMA
3   43768720  943.597705  1.260216e+06 -0.661199  0.553149  SARIMA
4   44072192   99.527906  1.350636e+04 -2.741304  0.951975  SARIMA

In [5]:
sarima["mae"].mean(), sarima["mape"].mean(), sarima["mse"].mean(), sarima["r2"].mean()

(273.6929401527031, 0.8195004360133036, 237269.7152679834, -2.3988555998383063)

In [9]:
sarima["mae"].mean(), sarima["mape"].mean(), sarima["mse"].mean(), sarima["r2"].mean()

(336.5266847396751, 0.920912927880142, 443991.29083541996, -2.8809265847096577)

## MLP

In [5]:
mlp = pd.read_parquet("MLP-long-time.parquet")
mlp.head()

        node          mae           mse         r2      mape model
0  125960550     6.191991  6.200018e+01  -1.110384  0.480837   MLP
1  230565994    37.912624  4.140325e+03 -16.037693  4.703748   MLP
2  258781031  1041.947876  1.312282e+06  -4.712078  0.961472   MLP
3   43768720  1498.926880  2.977606e+06  -2.929089  0.867413   MLP
4   44072192    60.753605  5.572439e+03  -0.544535  0.833653   MLP

In [7]:
mlp["mae"].mean(), mlp["mape"].mean(), mlp["mse"].mean(), mlp["r2"].mean()

(59810.19528784752, 646.7259085446597, 220165016172.8915, -12802088.770622874)

## LSTM

In [15]:
lstm = pd.read_parquet("LSTM-long-time.parquet")
lstm.head()

        node          mae           mse        r2      mape model
0  125960550     5.577831  5.180875e+01 -0.763484  0.488127  LSTM
1  230565994    11.508994  3.085341e+02 -0.269637  0.656303  LSTM
2  258781031  1066.038574  1.366177e+06 -4.946671  0.988144  LSTM
3   43768720  1637.347656  3.438745e+06 -3.537583  0.990983  LSTM
4   44072192    83.582268  1.057674e+04 -1.931597  0.708885  LSTM

In [16]:
lstm["mae"].mean(), lstm["mape"].mean(), lstm["mse"].mean(), lstm["r2"].mean()

(364.78130407333373,
 0.7897243946790695,
 506182.84195556643,
 -2.3298051595687865)

## GRU

In [13]:
gru = pd.read_parquet("GRU-long-time.parquet")
gru.head()

        node          mae           mse        r2      mape model
0  125960550     5.602227  5.278165e+01 -0.796600  0.441580   GRU
1  230565994    10.937225  2.801380e+02 -0.152785  0.681046   GRU
2  258781031  1058.061035  1.349232e+06 -4.872915  0.978135   GRU
3   43768720  1628.242432  3.409010e+06 -3.498347  0.982095   GRU
4   44072192    85.060402  1.083170e+04 -2.002265  0.729783   GRU

In [14]:
gru["mae"].mean(), gru["mape"].mean(), gru["mse"].mean(), gru["r2"].mean()

(363.3101372241974, 0.7893513292074203, 501545.3331302643, -2.3276140332221984)